language: node_js
node_js:
  - "0.10"
before_install:
  - gem install sass
  - npm install -g grunt-cli
  - npm install -g bower
before_script:
  - bower install
install: npm install
after_success: grunt coveralls