# username/repository
id: mistic100/jQuery-QueryBuilder
# name of the software
name: jQuery QueryBuilder
# current version of the software
version: 2.5.0
# links to file/dir viewers
treeUrl: https://github.com/mistic100/jQuery-QueryBuilder/tree/master
blobUrl: https://github.com/mistic100/jQuery-QueryBuilder/blob/master
cdnUrl: https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon:

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
download:
  popup: true
  url: https://github.com/mistic100/jQuery-QueryBuilder/archive/master.zip
  bower: jQuery-QueryBuilder
  npm: jQuery-QueryBuilder
  cdn:
    url: https://www.jsdelivr.com/package/npm/jQuery-QueryBuilder
    img: http://querybuilder.js.org/assets/images/jsdelivr-logo.png
    name: jsDelivr

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: true

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/mistic100/jQuery-QueryBuilder
  - title: StrangePlanet
    url: http://www.strangeplanet.fr

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/mistic100/jQuery-QueryBuilder
  - title: Issues
    url: https://github.com/mistic100/jQuery-QueryBuilder/issues?state=open

# header
header:
  color1: "#0074d9"
  color2: "#001f3f"
  trianglify: true

# google analytics
analytics:
  account: UA-28192323-3
  domain: auto

# github button
githubButton:
  user: mistic100
  repo: jQuery-QueryBuilder

# twitter buttons
twitter:
  enabled: true
  via: mistic100
  hash: jQuery,QueryBuilder
  account: mistic100

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-redirect-from
